// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol";
import "@openzeppelin/contracts/utils/Strings.sol";
import "@openzeppelin/contracts/utils/Base64.sol";

/**
 * @title BeatstarCardNFT
 * @notice NFT contract for the "Poetry in Motion: th3v4ult" (PIM) ecosystem.
 * Stores card attributes and music stream URLs on-chain and generates dynamic
 * metadata fully on-chain.
 */
contract BeatstarCardNFT is ERC721, Ownable {
    using Strings for uint256;

    struct Card {
        uint256 day;
        string title;
        string rarity;
        uint256 edition;
        string audioUrl;       // URL to the music stream (animation_url in metadata)
        string coverUrl;       // URL to the card artwork (image in metadata)
        string proof;          // Special verification proof (e.g. proof_of_first)
        bool isEcho;           // Lifecycle echo flag
        uint256 echoGeneration;// Echo generation index
    }

    // Mapping from tokenId to Card details
    mapping(uint256 => Card) public cards;

    // Mapping of authorized backend minters
    mapping(address => bool) public isMinter;

    // Events
    event CardMinted(
        uint256 indexed tokenId,
        address indexed recipient,
        uint256 indexed day,
        string rarity,
        uint256 edition
    );
    event MinterStatusUpdated(address indexed minter, bool status);

    modifier onlyOwnerOrMinter() {
        require(msg.sender == owner() || isMinter[msg.sender], "Not authorized: must be owner or minter");
        _;
    }

    constructor(address initialOwner) 
        ERC721("Poetry in Motion: th3v4ult", "PIM") 
        Ownable(initialOwner) 
    {}

    /**
     * @notice Set minter status for a server backend/operator wallet.
     */
    function setMinter(address minter, bool status) external onlyOwner {
        isMinter[minter] = status;
        emit MinterStatusUpdated(minter, status);
    }

    /**
     * @notice Direct administrative mint by owner or authorized minter.
     * Useful for backend-sponsored gas-free minting.
     */
    function mintCard(
        address recipient,
        uint256 tokenId,
        uint256 day,
        string calldata title,
        string calldata rarity,
        uint256 edition,
        string calldata audioUrl,
        string calldata coverUrl,
        string calldata proof,
        bool isEcho,
        uint256 echoGeneration
    ) external onlyOwnerOrMinter {
        _safeMint(recipient, tokenId);
        cards[tokenId] = Card({
            day: day,
            title: title,
            rarity: rarity,
            edition: edition,
            audioUrl: audioUrl,
            coverUrl: coverUrl,
            proof: proof,
            isEcho: isEcho,
            echoGeneration: echoGeneration
        });
        emit CardMinted(tokenId, recipient, day, rarity, edition);
    }

    /**
     * @notice Signature-based minting where the user calls the contract and pays gas,
     * providing a cryptographic signature generated by the authorized backend.
     */
    function mintCardWithSignature(
        address recipient,
        uint256 tokenId,
        uint256 day,
        string calldata title,
        string calldata rarity,
        uint256 edition,
        string calldata audioUrl,
        string calldata coverUrl,
        string calldata proof,
        bool isEcho,
        uint256 echoGeneration,
        bytes calldata signature
    ) external payable {
        // 1. Recreate the hashed message signed by the minter
        bytes32 messageHash = keccak256(
            abi.encodePacked(
                recipient,
                tokenId,
                day,
                title,
                rarity,
                edition,
                audioUrl,
                coverUrl,
                proof,
                isEcho,
                echoGeneration
            )
        );
        bytes32 ethSignedMessageHash = MessageHashUtils.toEthSignedMessageHash(messageHash);

        // 2. Recover the signer address
        address signer = ECDSA.recover(ethSignedMessageHash, signature);

        // 3. Verify the signer is authorized
        require(
            signer == owner() || isMinter[signer],
            "Unauthorized signature"
        );

        // 4. Mint the NFT and record parameters
        _safeMint(recipient, tokenId);
        cards[tokenId] = Card({
            day: day,
            title: title,
            rarity: rarity,
            edition: edition,
            audioUrl: audioUrl,
            coverUrl: coverUrl,
            proof: proof,
            isEcho: isEcho,
            echoGeneration: echoGeneration
        });
        emit CardMinted(tokenId, recipient, day, rarity, edition);
    }

    /**
     * @notice Dynamic tokenURI function that outputs base64-encoded metadata fully on-chain.
     */
    function tokenURI(uint256 tokenId) public view override returns (string memory) {
        _requireOwned(tokenId);

        Card memory card = cards[tokenId];

        // Zero pad the day index for naming structure: e.g. Day 001
        string memory dayStr = card.day.toString();
        string memory paddedDay = card.day < 10 
            ? string(abi.encodePacked("00", dayStr)) 
            : (card.day < 100 ? string(abi.encodePacked("0", dayStr)) : dayStr);

        // Build base JSON properties
        bytes memory json = abi.encodePacked(
            '{"name": "Poetry in Motion: th3v4ult - Day ', paddedDay, ' : ', card.title, '",',
            '"description": "Poetry in Motion: th3v4ult Gen 0 Archive - Day ', dayStr, ' of 365.",',
            '"image": "', card.coverUrl, '",',
            '"animation_url": "', card.audioUrl, '",',
            '"attributes": ['
        );

        // Build attributes structure
        bytes memory attrs = abi.encodePacked(
            '{"trait_type": "Day", "value": ', dayStr, '},',
            '{"trait_type": "Rarity", "value": "', card.rarity, '"},',
            '{"trait_type": "Edition", "value": ', card.edition.toString(), '},',
            '{"trait_type": "Proof", "value": "', card.proof, '"},',
            '{"trait_type": "Lifecycle", "value": "', card.isEcho ? "echo" : "original", '"},',
            '{"trait_type": "Echo Generation", "value": ', card.echoGeneration.toString(), '}'
        );

        bytes memory jsonClosing = abi.encodePacked(
            ']}'
        );

        // Encode JSON to base64
        string memory base64Json = Base64.encode(
            abi.encodePacked(json, attrs, jsonClosing)
        );

        return string(abi.encodePacked("data:application/json;base64,", base64Json));
    }
}
