-- ============================================================================
-- RLS HARDENING: Ensure anon clients cannot directly write economy tables
-- Generated by audit 2026-09-15
-- ============================================================================

-- global_supply: read-only for everyone, write only via service role (vault-engine)
ALTER TABLE public.global_supply ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "supply_read_all" ON public.global_supply;
CREATE POLICY "supply_read_all" ON public.global_supply
  FOR SELECT USING (true);
-- No INSERT/UPDATE/DELETE policy = anon clients cannot write

-- profiles: each user can only read/update their own row
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "profiles_own" ON public.profiles;
CREATE POLICY "profiles_own" ON public.profiles
  FOR ALL USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- vault_collections: each user owns their own cards
ALTER TABLE public.vault_collections ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "vault_own" ON public.vault_collections;
CREATE POLICY "vault_own" ON public.vault_collections
  FOR ALL USING (auth.uid() = owner_id)
  WITH CHECK (auth.uid() = owner_id);

-- echo_pool: read-only for authenticated users, write only via service role
ALTER TABLE public.echo_pool ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "echo_pool_read" ON public.echo_pool;
CREATE POLICY "echo_pool_read" ON public.echo_pool
  FOR SELECT TO authenticated USING (true);

-- gameplay_records: users can insert/read their own records
ALTER TABLE public.gameplay_records ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "gameplay_own" ON public.gameplay_records;
CREATE POLICY "gameplay_own" ON public.gameplay_records
  FOR ALL USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- user_cards: users own their own cards (applied only if table exists)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'user_cards'
  ) THEN
    ALTER TABLE public.user_cards ENABLE ROW LEVEL SECURITY;
    EXECUTE 'DROP POLICY IF EXISTS "user_cards_own" ON public.user_cards';
    EXECUTE $policy$
      CREATE POLICY "user_cards_own" ON public.user_cards
        FOR ALL USING (auth.uid() = user_id)
        WITH CHECK (auth.uid() = user_id)
    $policy$;
  END IF;
END;
$$;

-- releases (song catalog): public read, no client writes
ALTER TABLE public.releases ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "releases_read_all" ON public.releases;
CREATE POLICY "releases_read_all" ON public.releases
  FOR SELECT USING (true);
